# Generated by Django 4.2.4 on 2023-08-28 04:54

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CategoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('record_type', models.CharField(choices=[('유무', 'existence'), ('강도', 'strength'), ('시각', 'time')], default='유무', max_length=10)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='correlation.category')),
            ],
        ),
        migrations.CreateModel(
            name='StatisticsResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=200)),
                ('target_year', models.IntegerField(default=2023)),
                ('target_month', models.IntegerField(null=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('category_item_x', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='statistics_result_x', to='correlation.categoryitem')),
                ('category_item_y', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='statistics_result_y', to='correlation.categoryitem')),
            ],
        ),
        migrations.CreateModel(
            name='CategoryItemData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(default=datetime.date.today)),
                ('created_time', models.TimeField(default=datetime.datetime.now)),
                ('figure', models.IntegerField(null=True)),
                ('category_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='correlation.categoryitem')),
            ],
        ),
    ]
