# Generated by Django 4.2.4 on 2023-08-31 02:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('correlation', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='statisticsresult',
            name='account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='statisticsresult',
            name='category_item_x',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='statistics_result_x', to='correlation.categoryitem'),
        ),
        migrations.AddField(
            model_name='statisticsresult',
            name='category_item_y',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='statistics_result_y', to='correlation.categoryitem'),
        ),
        migrations.AddField(
            model_name='categoryitemdata',
            name='category_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='correlation.categoryitem'),
        ),
        migrations.AddField(
            model_name='categoryitem',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='correlation.category'),
        ),
        migrations.AddField(
            model_name='category',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
