# Generated by Django 4.1.3 on 2022-12-20 05:18

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('correlation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatisticsResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='categoryitem',
            name='record_type',
            field=models.CharField(choices=[('유무', 'Existence'), ('강도', 'Strength')], default='유무', max_length=10),
        ),
        migrations.CreateModel(
            name='CategoryItemData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recorded_date', models.DateField(default=datetime.date.today)),
                ('recorded_time', models.TimeField(default=datetime.datetime.now)),
                ('existence', models.BooleanField()),
                ('strength', models.IntegerField()),
                ('category_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='correlation.categoryitem')),
            ],
        ),
    ]
