# Generated by Django 4.1.3 on 2022-12-20 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correlation', '0002_statisticsresult_categoryitem_record_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryitemdata',
            name='name',
            field=models.CharField(default=None, max_length=10),
        ),
    ]
