# Generated by Django 4.2.4 on 2023-09-07 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correlation', '0003_monthlymean'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlymean',
            name='content',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='monthlymean',
            name='mean',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
