# Generated by Django 4.1.3 on 2022-12-24 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correlation', '0006_rename_recorded_date_categoryitemdata_created_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryitem',
            name='record_type',
            field=models.CharField(choices=[('유무', 'existence'), ('강도', 'strength'), ('시각', 'time')], default='유무', max_length=10),
        ),
    ]
